host_key_checking : False
ansible_user: developer
ansible_ssh_pass: C1sco12345
ansible_port: 8181
ansible_python_interpreter: /usr/local/bin/python3
ansible_network_os: ios
ansible_connection: network_cli
validate_file: "validation.yml"