---
- name: NETCONF sample 1
  hosts: iosxe
  gather_facts: False

  tasks:
    - name: Execute the get_config RPC
      netconf_get:
        host: "{{inventory_hostname}}"
        port: "{{netconf_port}}"
        username: "{{ansible_user}}"
        password: "{{ansible_password}}"
        hostkey_verify: False
        display: json
      register: result
    - name: Print the configuration as JSON
      debug:
        var: result.output