---
- name: Configure loopback using ios_interface
  hosts: iosxe
  gather_facts: no

  tasks:
    - name: create loopback interface
      napalm_install_config:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh_pass }}"
        dev_os: "ios"
        optional_args:
          port: 8181
        config_file: 'loopbacks.txt'
        commit_changes: true
        replace_config: false
        get_diffs: True
        diff_file: 'diff'
        

