---
- name: Configure loopback using ios_interface
  hosts: iosxe
  gather_facts: no
  vars_files:
    - vars/loopbacks.yaml

  tasks:
    - name: get facts from device
      napalm_get_facts:
        hostname={{ inventory_hostname }}
        username={{ ansible_ssh_user }}
        password={{ ansible_ssh_pass }}
        dev_os={{ os }}
        filter='facts,interfaces'
      register: result

    - name: print data
      debug: var=result


