
ansible_user: 'developer'
ansible_password: 'C1sco12345'
ansible_connection: "httpapi"
ansible_network_os: "restconf"
ansible_httpapi_use_ssl: true
ansible_httpapi_port: 9443
ansible_httpapi_validate_certs: false
ansible_httpapi_restconf_root: "/restconf"
