
ansible_user: 'developer'
ansible_password: 'C1sco12345'
ansible_connection: "httpapi"
ansible_network_os: "restconf"
ansible_httpapi_use_ssl: true
ansible_httpapi_port: 9443
ansible_httpapi_validate_certs: false
ansible_httpapi_restconf_root: "/restconf"


loopback_interfaces: 
    interface:
        - name: "Loopback200001"
          description: "Loopback via Ansible Restconf"
          type: "iana-if-type:softwareLoopback"
          enabled: true
          ietf-ip:ipv4:
            address:
              - ip: "10.0.12.12"
                netmask: "255.255.255.255"
        - name: "Loopback200002"
          description: "Loopback via Ansible Restconf"
          type: "iana-if-type:softwareLoopback"
          enabled: true
          ietf-ip:ipv4:
            address:
              - ip: "10.0.12.13"
                netmask: "255.255.255.255"
        - name: "Loopback200003"
          description: "Loopback via Ansible Restconf"
          type: "iana-if-type:softwareLoopback"
          enabled: true
          ietf-ip:ipv4:
            address:
              - ip: "10.0.12.14"
                netmask: "255.255.255.255"