- name: Full ACI configuration
  hosts: apic
  connection: local
  gather_facts: False
  vars_files:
    - vars/variables_aci.yml
  
  tasks:
    - name: Task 01 - Ensure Applications Tenant Exists
      aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        descr: "Tenant Created Using Ansible"
      tags: tenant, vrf, bd, filter, contract, app, epg

    - name: Task 02 - Ensure VRF Exists
      aci_vrf:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        vrf: "{{ vrf }}"
        descr: "VRF Created Using Ansible"
      tags: vrf, bd

    - name: Task 03 - Ensure Bridge Domains and Exist
      aci_bd:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        bd: "{{ item.bd | default('prod_bd') }}"
        vrf: "{{ vrf }}"
      with_items: "{{ bridge_domains }}"
      tags: bd
    
    - name: Task 03A - Attach L3Out to BD
      aci_bd_to_l3out:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        bd: "{{ item.bd }}"
        tenant: "{{ tenant }}"
        l3out: "labinfra-l3out-ro"
      with_items: "{{ bridge_domains }}"
      tags: bd

    - name: Task 04 - Ensure Bridge Domains Have Subnets
      aci_bd_subnet:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        bd: "{{ item.bd }}"
        gateway: "{{ item.gateway }}"
        mask: "{{ item.mask }}"
        scope: ["public", "shared"]
      with_items: "{{ bridge_domains }}"

    - name: Task 05A - Ensure Tenant Filters Exist - ICMP
      aci_filter:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        filter: "{{ item.filter }}"
        descr: "Filter Created Using Ansible"
      with_items: "{{ filters_icmp }}"
      tags: filter, contract

    - name: Task 06A - Ensure Filters Have Filter Entries - ICMP
      aci_filter_entry:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        filter: "{{ item.filter }}"
        entry: "{{ item.entry }}"
        ether_type: "ip"
        ip_protocol: "{{ item.protocol }}"
      with_items: "{{ filters_icmp }}"
      tags: filter, contract

    - name: Task 07A - Ensure Tenant Contracts Exist - ICMP
      aci_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        contract: "{{ item.contract }}"
        scope: "context"
        description: "Contract Created Using Ansible"
      with_items: "{{ contracts_icmp }}"
      tags: contract

    - name: Task 08A - Ensure Contracts Have Contract Subjects - icmp
      aci_contract_subject:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        contract: "{{ item.contract }}"
        subject: "{{ item.subject }}"
      with_items: "{{ contracts_icmp }}"
      tags: contract

    - name: Task 09A - Ensure Contract Subjects Have Filters - icmp
      aci_contract_subject_to_filter:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        contract: "{{ item.contract }}"
        subject: "{{ item.subject }}"
        filter: "{{ item.filter }}"
      with_items: "{{ contracts_icmp }}"
      tags: contract

    - name: Task 09B - Ensure Tenant Contracts Exist - Common
      aci_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "common"
        contract: "ctr_internet"
        scope: "context"
        description: "Contract Created Using Ansible"
      tags: contract

    - name: Task 05 - Ensure Tenant Filters Exist - Other protocols
      aci_filter:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        filter: "{{ item.filter }}"
        descr: "Filter Created Using Ansible"
      with_items: "{{ filters }}"
      tags: filter, contract

    - name: Task 06 - Ensure Filters Have Filter Entries - other protocols
      aci_filter_entry:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        filter: "{{ item.filter }}"
        entry: "{{ item.entry }}"
        ether_type: "ip"
        ip_protocol: "{{ item.protocol }}"
        dst_port_start: "{{ item.port }}"
        dst_port_end: "{{ item.port }}"
        stateful: yes
      with_items: "{{ filters }}"
      tags: filter, contract

    - name: Task 07 - Ensure Tenant Contracts Exist
      aci_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        contract: "{{ item.contract }}"
        scope: "context"
        description: "Contract Created Using Ansible"
      with_items: "{{ contracts }}"
      tags: contract

    - name: Task 08 - Ensure Contracts Have Contract Subjects
      aci_contract_subject:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        contract: "{{ item.contract }}"
        subject: "{{ item.subject }}"
      with_items: "{{ contracts }}"
      tags: contract
    
    - name: Task 09 - Ensure Contract Subjects Have Filters
      aci_contract_subject_to_filter:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        contract: "{{ item.contract }}"
        subject: "{{ item.subject }}"
        filter: "{{ item.filter }}"
      with_items: "{{ contracts }}"
      tags: contract

    - name: Task 10 - Ensure Application Exists
      aci_ap:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        descr: "App Profile Created Using Ansible "
      tags: app, epg

    - name: Task 11 - Ensure Application EPGs Exists
      aci_epg:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        bd: "{{ item.bd }}"
        descr: "EPG Created Using Ansible"
      with_items: "{{ epgs }}"
      tags: epg

    - name: Task 12 - Ensure Domain Is Bound To EPG
      aci_epg_to_domain:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        domain: "dvs-demo-dynamic"
        domain_type: "vmm"
        vm_provider: "vmware"
      with_items: "{{ epgs }}"
      tags: epg

    - name: Task 13 - Ensure EPGs Have Contracts
      aci_epg_to_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        contract: "{{ item.contract }}"
        contract_type: "{{ item.contract_type }}"
      with_items: "{{ epg_contracts }}"
      tags: epg
    
    - name: Task 13A - Ensure EPGs Have Common Contract ctr-extnet
      aci_epg_to_contract:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: False
        state: "present"
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        contract: "ctr-extnet"
        contract_type: "consumer"
      with_items: "{{ epg_contracts }}"
      tags: epg