#simple IOS config in ansible
---
- name: Getting started
  hosts: iosxe
  gather_facts: no

  tasks:
  - name: GATHERING FACTS
    ios_facts:
      gather_subset: hardware

  - name: run multiple commands
    ios_command:
      commands: 
        - show version
        - show ip interface brief
      wait_for:
        - result[0]
        - result[1]
  
 

