---
- name: Configure loopback using ios_interface
  hosts: iosxe
  gather_facts: no

  tasks:
    - name: Merge provided configuration with device configuration
      ios_interfaces:
        config:
          - name: GigabitEthernet3
            description: 'Configured by Ansible Network'
          - name: Loopback100
            description: 'Loopback Configured by Ansible Network'
        state: merged
