# Define list of hosts
---
hosts:
  - name: sbx-iosxr-mgmt.cisco.com
    username: admin
    password: C1sco12345
    port: 8181
    cmd: "show running-config"
    type: cisco_xr
  - name: ios-xe-mgmt-latest.cisco.com
    username: developer
    password: C1sco12345
    port: 8181
    cmd: "show running-config"
    type: cisco_xe